#ifndef _GLOBALIMAGETABLE_H_
#define _GLOBALIMAGETABLE_H_
#include <ultra64.h>
#include <bondtypes.h>

enum MONIMGIDS {
    IMGBOND, //0x0
    IMGLOCATION,
    IMGBEGINARMING,
    IMGTARGET,
    IMGSEVERNAYA, //0x4
    IMGBREAKTARGET,
    IMGAIMER,
    IMGEARTH,
    IMGDESKTOPBANG, //0x8
    IMGHEATMAP,
    IMG3DMATH,
    IMGDESKTOPBARS,
    IMG2DMATH, //0xC
    IMGSATELLITE,
    IMGDESKTOP,
    IMGDESKTOPSTAGGERED,
    IMGCUBE1, //0x10
    IMGSHUTTLE1,
    IMGSHUTTLE2,
    IMGEARTHFULL1,
    IMGEARTHFULL2, //0x14
    IMGBLUESTARS,
    IMGGALAXY1,
    IMGGALAXY2,
    IMGEARTHTEXT, //0x18
    IMGTARGETEARTH,
    IMGGALAXY3,
    IMGSTATIC,
    IMGSINE, //0x1C
    IMGTEXT,
    IMGBARS,
    IMGSQUARES,
    IMGFIST1, //0x20
    IMGFIST2,
    IMGFIST3,
    IMGFIST4,
    IMGSKATEBOARD4, //0x24
    IMGSKATEBOARD1,
    IMGSKATEBOARD2,
    IMGSKATEBOARD3,
    IMGTALK1, //0x28
    IMGTALK2,
    IMGTALK3,
    IMGTALK4,
    IMGWORLDMAP, //0x2C
    IMGCUBE2,
    IMGCUBE3,
    IMGCUBE4,
    IMGTRIANGLE, //0x30
    IMGKEYBOARDKEY
};

enum MAINFOLDERIMGIDS {
    IMG_COPY,
    IMG_DEL,
    IMG_SEL,
    IMG_X,
    IMG_CHECK,
    IMG_DOT
};

enum MPSELECTIMGIDS {
    IMG_MP_BUNKER2,
    IMG_MP_CAVERNS,
    IMG_MP_ARCHIVES,
    IMG_MP_DAM,
    IMG_MP_FACILITY,
    IMG_MP_RUNWAY,
    IMG_MP_FRIGATE,
    IMG_MP_STATUE,
    IMG_MP_CRADLE,
    IMG_MP_AZTEC,
    IMG_MP_EGYPT,
    IMG_MP_DEPOT,
    IMG_MP_TEMPLE,
    IMG_MP_BASEMENT,
    IMG_MP_COMPLEX,
    IMG_MP_CAVES,
    IMG_MP_RANDOM
};

enum MPCHRSELIMAGES {
    IMG_MPC_BROSNAN,
    IMG_MPC_MOORE,
    IMG_MPC_DALTON,
    IMG_MPC_CONNERY,
    IMG_MPC_BORIS,
    IMG_MPC_OURUMOV,
    IMG_MPC_TREVELYAN,
    IMG_MPC_VALENTIN,
    IMG_MPC_XENIA,
    IMG_MPC_NATALYA,
    IMG_MPC_BARON,
    IMG_MPC_JAWS,
    IMG_MPC_MAYDAY,
    IMG_MPC_ODDJOB,
    IMG_MPC_RANDOM,
    IMG_MPC_MISHKIN
};


#endif
